version: '3'
services:
  apollo-server:
    build: ./server
    tty: true
    volumes:
      - ./server:/app/server
    ports:
      - "8080:4000"
    networks:
      - apollo-net  
  apollo-client:
    build: ./client
    tty: true
    volumes:
      - ./client:/app/client
    ports:
      - "8081:3000"
    networks:
      - apollo-net  
networks:
  apollo-net:
    driver: bridge
